# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  sbtVersion: 1.2.8

steps:
- script: wget https://dl.bintray.com/sbt/debian/sbt-$(sbtVersion).deb
  displayName: 'Download SBT'

- script: sudo dpkg -i sbt-$(sbtVersion).deb
  displayName: 'Install SBT'

- script: sbt test:test
  displayName: 'Compile and run tests'
